# Sintaxe básico do PyTorch

Assim como o NumPy, o PyTorch é uma biblioteca de processamento vetorial/matroarcaç/tensorial. Operações sobre os tensores do PyTorch possuem sintaxe consideravelmente parecida com operações sobre tensores do Numpy

## Tipos de tensores

Você pode criar tensores do PyTorch de inúmeras formas! Vamos ver primeiro os tipos de tensores que estão ao nosso dispor. Para isso, vamos converter listas comuns do **Python** em tensors do PyTorch

In [6]:
import torch

list = [[1, 2, 3], [4, 5, 6]]

tensor = torch.Tensor(list)

print(tensor.dtype)
print(list)
print("")

tensor = torch.FloatTensor(list)

print(tensor.dtype)
print(list)
print("")

tensor = torch.DoubleTensor(list)

print(tensor.dtype)
print(list)
print("")


tensor = torch.LongTensor(list)

print(tensor.dtype)
print(list)
print("")

torch.float32
[[1, 2, 3], [4, 5, 6]]

torch.float32
[[1, 2, 3], [4, 5, 6]]

torch.float64
[[1, 2, 3], [4, 5, 6]]

torch.int64
[[1, 2, 3], [4, 5, 6]]



## Outras formas de instanciar tensores

### A partir de arrays Numpy

__*torch.from_numpy()*__

In [18]:
import numpy as np


array = np.random.rand(3, 4)

tensor = torch.from_numpy(array)

print(array)
print(array.dtype)
print("")
print(tensor)
print(tensor.dtype)

[[0.60294106 0.97366661 0.04129556 0.50940772]
 [0.09029864 0.67343186 0.47052895 0.18655834]
 [0.95244386 0.32086876 0.24397609 0.65128376]]
float64

tensor([[0.6029, 0.9737, 0.0413, 0.5094],
        [0.0903, 0.6734, 0.4705, 0.1866],
        [0.9524, 0.3209, 0.2440, 0.6513]], dtype=torch.float64)
torch.float64


### Tensores inicializados

Essas funções recebem como parâmetro o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:


__*torch.ones()*__ => Cria um tensor preenchido com zeros.

__*torch.zeros()*__ => Cria um tensor preenchido com uns.

__*torch.randn()*__ => Cria um tensor preencido com números aleatórios a partir de uma distribuição normal

In [16]:
tensor1 = torch.ones(2, 3)
tensor0 = torch.zeros(4, 5)
tensorRand = torch.randn(3, 3)

print(tensor1)
print(tensor0)
print(tensorRand)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.7343,  0.3146,  0.8961],
        [ 0.1550,  0.3605, -1.7047],
        [-1.0968,  0.8590,  0.2687]])


### Tensor para um array numpy

In [21]:
array = tensor.data.numpy()

print(type(tensor))
print(type(array))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### Indexação

De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, através da sintaxe de conchetes [].

In [28]:
print(tensorRand)
print("")

tensorRand[0, 2] = - 10

print(tensorRand)
print("")

print(tensorRand[0:2])
print("")
print(tensorRand[:, 2])
print("")
print(tensorRand[0, 2])
print(tensorRand[0, 2].size())



tensor([[  0.7343,   0.3146, -10.0000],
        [  0.1550,   0.3605,  -1.7047],
        [ -1.0968,   0.8590,   0.2687]])

tensor([[  0.7343,   0.3146, -10.0000],
        [  0.1550,   0.3605,  -1.7047],
        [ -1.0968,   0.8590,   0.2687]])

tensor([[  0.7343,   0.3146, -10.0000],
        [  0.1550,   0.3605,  -1.7047]])

tensor([-10.0000,  -1.7047,   0.2687])

tensor(-10.)
torch.Size([])


### Operações com tensores

A função .item() utilizada anteriormente extrai o número de um tensor que possui um único valor, permitindo realizar operações numéricas do Python.

Vale ressaltar tambpem que operações entre tensores são realizados ponto a ponto, operando cada elemente (i, j) do tensor t1, com o elemento (i, j) do tensor t2

In [34]:
# tensor = tensorRand[0:2, :]

print(tensor)
print(tensor1)

print(torch.mm(tensor, tensor1.T))

tensor([[  0.7343,   0.3146, -10.0000],
        [  0.1550,   0.3605,  -1.7047]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-8.9511, -8.9511],
        [-1.1892, -1.1892]])


### Função .size() e .view()

Uma operação **importantíssima** na manipulação de tensores para Deep Learning é a reorganização das suas dimensções, Dessa forma podemos, por exemplo, **linearizar um tensor n-dimensional**.

In [46]:
tensor = torch.randn(2, 2, 3)

print(tensor)

print("")

print(tensor.size())

print("")

tensor = tensor.view(12)
print(tensor.size())
print(tensor)

print("")

tensor = tensor.view(4, 3)
print(tensor.size())
print(tensor)

print("")

tensor = tensor.view(2, 2, 3 )
tensor = tensor.view(tensor.size(0), -1)
print(tensor.size())
print(tensor)

tensor([[[-0.0656, -0.0189, -0.7643],
         [ 0.1161,  0.6317, -1.2649]],

        [[-1.1579,  1.0589,  0.1476],
         [-1.5816, -0.0884,  2.5035]]])

torch.Size([2, 2, 3])

torch.Size([12])
tensor([-0.0656, -0.0189, -0.7643,  0.1161,  0.6317, -1.2649, -1.1579,  1.0589,
         0.1476, -1.5816, -0.0884,  2.5035])

torch.Size([4, 3])
tensor([[-0.0656, -0.0189, -0.7643],
        [ 0.1161,  0.6317, -1.2649],
        [-1.1579,  1.0589,  0.1476],
        [-1.5816, -0.0884,  2.5035]])

torch.Size([2, 6])
tensor([[-0.0656, -0.0189, -0.7643,  0.1161,  0.6317, -1.2649],
        [-1.1579,  1.0589,  0.1476, -1.5816, -0.0884,  2.5035]])


###  GPU Cast

para que o seu script dê suporte a infraestrutura com e sem GPU, é importante definir o dispositivo no início do seu código de acordo com a verificação apresentada a seguir. Essa definição será utilizada toda vez que precisarmos subir os valores na GPU, como os pesos da rede, os gradientes e etc.

In [50]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
    
tensor = torch.randn(10)
tensor = tensor.to(device)
    
print(device)
print(tensor)

cuda
tensor([ 0.7854, -0.5989,  0.6153,  1.8983, -0.6095,  0.4376, -1.5621,  0.0246,
         0.2784, -0.3381], device='cuda:0')


### Atividade

Pensando nisso, crie um tensor aleatório tns1 com a dimensionalidade 7 x 7 x 3 e um outro tensor aleatório tns2 de 147 x 1. Modificando apenas tns1 some os dois tensores.

In [53]:
tensor1 = torch.randn(7, 7, 3)
tensor2 = torch.randn(147, 1)

tensor1 = tensor1.view(-1, 1)

print(tensor1)

print(tensor1 + tensor2)

tensor([[ 0.4583],
        [-0.9572],
        [ 0.0732],
        [ 1.8609],
        [ 1.0095],
        [-1.7584],
        [-1.9615],
        [-0.5258],
        [-0.0541],
        [-1.0323],
        [-1.4489],
        [-0.0241],
        [ 0.8427],
        [-1.4269],
        [-0.3372],
        [-1.9785],
        [-0.8502],
        [-0.1873],
        [ 0.4898],
        [ 1.2227],
        [-0.5585],
        [-0.7771],
        [-0.7542],
        [-0.5770],
        [-2.0674],
        [-0.7758],
        [ 0.4291],
        [ 0.0648],
        [ 1.2425],
        [ 0.4871],
        [ 0.0556],
        [ 0.9315],
        [ 1.5464],
        [ 1.3146],
        [-0.4789],
        [ 0.5943],
        [-1.3614],
        [ 2.3232],
        [-0.7158],
        [ 0.8363],
        [ 0.8630],
        [ 0.6128],
        [-2.5583],
        [-0.6894],
        [ 0.4073],
        [-0.6969],
        [-1.2571],
        [-0.8624],
        [-0.9677],
        [-1.5707],
        [ 0.4641],
        [ 0.5073],
        [ 2.